fn<-read.csv("./consumption.txt",skip=66637,nrows=2879,sep=";",header=TRUE)
par(mfrow = c(2,2), mar = c(4,4,2,1))
fn[[3]]<-as.numeric(fn[[3]])
fn[[1]] <- strptime(paste(fn[[1]],fn[[2]]), "%d/%m/%Y %H:%M:%S")
with(fn, {
plot(fn[[1]],fn[[3]],type="l",xlab="",ylab="Global Active Power (kilowatts)")
plot(fn[[1]],fn[[5]],type="l",xlab="datetime",ylab="Voltage")
plot(fn[[1]],fn[[7]],type="l",xlab="",ylab="Energy sub metering")
lines(fn[[1]],fn[[8]],type="l",col="red")
lines(fn[[1]],fn[[9]],type="l",col="blue")
legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(fn[[1]],fn[[4]],type="l",xlab="datetime",ylab="Global_reactive_power")})
dev.copy(png,file="plot4.png",width=480, height=480)
dev.off()
